version: '3'

volumes:
  pg_data_production:
  static_volume:
  media:

services:

  db:
    image: postgres:13.10
    env_file: .env
    volumes:
      - pg_data_production:/var/lib/postgresql/data

  backend:
    image: sofary0/kittygram_backend
    env_file: .env
    depends_on:
      - db
    volumes:
      - static_volume:/backend_static
      - media:/app/media/

  frontend:
    image: sofary0/kittygram_frontend
    env_file: .env
    command: cp -r /app/build/. /frontend_static/
    volumes:
      - static_volume:/frontend_static

  gateway:
    image: sofary0/kittygram_gateway
    env_file: .env
    depends_on:
      - backend
    volumes:
      - static_volume:/static/
      - media:/app/media/
    ports:
      - 9000:80
      